### ISSUE TITLE
Ausarbeitung Seitenstruktur

### ISSUE THREAD

**Issue by mootari** [drupal-usergroup-berlin/dug-website#13]
Seiten, Inhalte, Pfade und Verlinkungen sind zu definieren.

**Comment by mootari** [comment]
Aktueller Stand: http://www.gliffy.com/go/publish/10275409

**Comment by Stolzenhain** [comment]
Sorry, aber nachdem ich mir noch 1 Kopie gezogen hatte die Frage: 
- Welche Views fehlen noch?

sowie: 
- Könnten wir die System-Pfade mit in die Struktur aufnehmen, um den Testcase besser durchgehen zu können?

**Comment by mootari** [comment]
> Welche Views fehlen noch?

Soweit ich das gerade auf dem Schirm habe dürften keine Views fehlen. Es kann jedoch sein, dass sich während der Umsetzung noch Bedarf für weitere Varianten abzeichnet.

> Könnten wir die System-Pfade mit in die Struktur aufnehmen, um den Testcase besser durchgehen zu können?

Können wir gern machen - wie aber bereits in Slack angemerkt, will ich schnellstmöglich von gliffy weg, weil keine ernsthaften Exportmöglichkeiten vorhanden sind. Ich prüfe gerade, ob ninjamock eine geeignete Alternative ist.

**Comment by Stolzenhain** [comment]
Stimmt! Mark meinte richtig: Hat jetzt keinen Vorrang zeigte mir direkt alle schon umgesetzen View-Integrationen im Template. Alle weiteren Notizen unseres Gespräsch leichter verdaulich als [Wiki-Page](https://github.com/drupal-usergroup-berlin/dug-website/wiki/PM).

**Comment by mootari** [comment]
Link nach https://github.com/drupal-usergroup-berlin/dug-website/wiki/Seitenstruktur gepackt. Da es sich nur um einen grobe Struktur handelt, sollten Detailfragen in separaten Issues geklärt werden.
