### ISSUE TITLE
User Account - Drupal.Org Id widget als Textfield

### ISSUE THREAD

**Issue by pektinasen** [drupal-usergroup-berlin/dug-website#14]
Das Ganzzahlen Widget hat die Hoch/Runter-Buttons an der Seite und es kann kein anderes Widget fuer ganzzahlen ausgewaehlt werden.

Vorschlag:
hook_form_alter und aendere das widget in ein text feld

**Comment by webflo** [comment]
Ich hab das Feld in ein Link-Field konvertiert, dann brauch man nicht die Drupal.og User ID auf der Website suchen.
