### ISSUE TITLE
Integration bzw. Strategie für Meetup

### ISSUE THREAD

**Issue by mootari** [drupal-usergroup-berlin/dug-website#26]
Wie von @Stolzenhain bereits vorgeschlagen, sollten wir einen Weg finden die DUGs auch über meetup.com anzukündigen. Eine kurze Suche nach Drupal zeigt etliche User Groups mit jeweils hunderten, wenn nicht tausenden von Mitgliedern. Da ein ähnliches Potential höchstwahrscheinlich auch für Berlin existiert, kann es sich die DUG m.E. nicht leisten dieses zu verschenken.

Falls das Hauptproblem die "Wer kommt"-Funktion ist, bin ich im Zweifelsfall dafür diese zu kicken. In der Regel bildet sie ohnehin nicht die tatsächliche Teilnahme ab und vermittelt im schlimmsten Fall ein falsches Bild vom tatsächlich bestehenden Interesse an einem Treffen.

**Comment by Stolzenhain** [comment]
Hallo! 2 Punkte: 
1. Wenn ich das richtig verstanden hatte, steht die „Wer-kommt“-Funktion ja nicht auf Prio 1 zum Start. In Drupal 7 hätte ich das per [Rules Link](https://www.drupal.org/project/rules_link) erledigt, aber da gibt's ja noch nichtmal ein Release von Rules selbst. Sicher gibt es bald/schon eine Best-Practice für 8. 
2. Bei der Meetup-Sache geht's auch um [englische Nutzer](http://www.meetup.com/de-DE/drupal-Berlin/): Mein schwedischer Kollege z.B., der auch Modul-Contrib ist, konnte mit einer rein deutschen UG wenig anfangen– hier wäre womöglich schon mit einer englischen Info auf der Homepage ein erster Schritt getan.

**Comment by markomat** [comment]
Bitte lasst uns in diesen Issues nur über die DUG-Webseite austauschen, nicht über DUG-Marketing oder ähnliches. Wenn ihr die meetup-Seite der DUG erstellen und pflegen(!) wollt, dann macht das.
Bisher hat sich die Mehrheit der Gruppe dagegen ausgesprochen, eine weitere Plattform für die Treffen zu bespielen.

**Comment by markomat** [comment]
Ich schliesse dieses Issue, weil wir das Thema bereits auf Slack weiterführen
