### ISSUE TITLE
Begriff für "Events" festlegen

### ISSUE THREAD

**Issue by mootari** [drupal-usergroup-berlin/dug-website#27]
Während des Sprint-WE hatten wir fast ausschließlich den Begriff "Events" verwendet. Während das intern völlig in Ordnung ist, verwendet die aktuelle Seite jedoch "Termine" für den Menüpunkt und "Veranstaltungen" für die Auflistung. Ich bin sehr dafür englische Begriffe wo möglich zu vermeiden (wir haben immerhin bereits "Talks") und schlage vor, dass wir seitenweit "Termine" verwenden.

**Comment by Stolzenhain** [comment]
Ist auch verständlicher. Nicht alle Termine sind Veranstaltungen.

**Comment by markomat** [comment]
"Termine" it is.
