### ISSUE TITLE
Fix/Patch für Paragraphs-Problem (EntityChangedConstraint violation) anwenden

### ISSUE THREAD

**Issue by mootari** [drupal-usergroup-berlin/dug-website#32]
Schritte:
1. Bearbeitung der Startseite, Erstellen einer neuen Revision.
2. Bearbeitung der Startseite, Deaktivieren von "Neue Revision erstellen"
3. Nach Speicherung wurden keine Paragraphs mehr ausgegeben.
4. Zurücksetzen auf vorhergehende Version.
5. Erneutes Bearbeiten und Speichern.
6. Speicherung wird geblockt mit der Meldung "Der Inhalt wurde entweder von einem anderen Benutzer bearbeitet oder Sie haben schon Änderungen gespeichert. Deshalb können diese Änderungen nicht gespeichert werden.".

**Comment by mootari** [comment]
Original-Text: "The content has either been modified by another user, or you have already submitted modifications. As a result, your changes cannot be saved." - Quelle: EntityChangedConstraint

**Comment by mootari** [comment]
Ursprung der violation sind die Paragraphs entities. Das Zurücksetzen der Revision scheint da einiges durcheinander gebracht zu haben.

**Comment by markomat** [comment]
Vor ein paar Monaten trat das gleiche Problem bei einem Projekt auf, bei dem ich beteiligt war. Ich bin optimistisch, dass ich die Lösung dafür organisieren kann.

**Comment by mootari** [comment]
@markomat Bin gerade dabei den Patch in https://www.drupal.org/node/2715855 zu testen.

**Comment by markomat** [comment]
@cisso: Dieses kleine Modul konnte das beschriebene Problem im anderen Projekt lösen:

[paragraphs_hack.zip](https://github.com/drupal-usergroup-berlin/dug-website/files/258039/paragraphs_hack.zip)

**Comment by mootari** [comment]
Yup, das macht im Kern das was der Patch auch macht. Changed wird dort komplett entfernt, da es wohl ohnehin obsolet ist.

**Comment by mootari** [comment]
@markomat @webflo Patch löst das Problem lokal. Pushen oder auf commit warten und solange Marks Workaround verwenden? (Patch löscht die paragraphs fields revision_timestamp und changed)

**Comment by markomat** [comment]
@cisso: Nimm doch einfach die Variante, die dir besser geeignet vorkommt. Wenn der patch funktioniert, dann fügen wir ihn in einer composer.patches.json hinzu, damit er beim Deployment angewendet wird. 
Alternativ tut es paragraphs_hack-Modul auch. Ist von Jan Stöckler und in anderen Projekten im Einsatz.

**Comment by markomat** [comment]
@cisso, ignorier bitte den Teil mit der composer.patches.json. die patches werden am Ende der composer.json gelistet.

**Comment by mootari** [comment]
@markomat Bin mit der Handhabung von Patches in composer vertraut ;)
