### ISSUE TITLE
Text über die Usergroup

### ISSUE THREAD

**Issue by markomat** [drupal-usergroup-berlin/dug-website#9]
Auf der Webseite findet sich ein Text, der über die Aktionen, die Geschichte und die Ziele der Usergroup informiert.

**Comment by markomat** [comment]
Textentwurf für die Startseite:

Die Drupal Usergroup Berlin ist ein lose Gruppe von Personen, die sich für das CMS Drupal begeistern.

An jedem 1. Donnerstag im Monat treffen sich die Mitglieder der Usergroup im betahaus in Berlin Kreuzberg. Bei den sog. Usergroup-Treffen gibt es Vorträge, Diskussionen und immer die Möglichkeit, mit anderen Drupalistas ins Gespräch zu kommen und Fragen zu Drupal zu stellen.

Die Drupal Usergroup ist eine offene Gemeinschaft, die jede/n willkommen heißt, die/der sich für Drupal interessiert. Egal ob Einsteiger oder "Daily Active User". 

Komm' doch auch zum nächsten Treffen – wir freuen uns darauf, dich kennenzulernen!

[ Das nächste Usergroup-Treffen findet am TT.MM. statt ]
[ Noch mehr Informationen über die Usergroup ]

**Comment by pektinasen** [comment]
Vorschlag:
jede/n willkommen heißt, die/der sich für Drupal interessiert

Ersetzen durch "alle Drupalinteressierte herzlichst willkommen heißt."

**Comment by markomat** [comment]
@pektinasen: habe deinen Vorschlag aufgenommen und den Text auf http://drupalberlin.rocks/ueber-uns entsprechend angepasst. Entschuldige bitte die extrem späte Reaktion.
